blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^(?P<post_pk>\d+)/comment/new/$', views.comment_new, name='comment_new'),
    url(r'^(?P<post_pk>\d+)/comment/(?P<pk>\d+)/edit/$', views.comment_edit, name='comment_edit'),
    url(r'^(?P<post_pk>\d+)/comment/(?P<pk>\d+)/delete/$', views.comment_delete, name='comment_delete'),
]

photowall/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace = 'blog')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
import re
from django import forms
from django.core.urlresolvers import reverse
from django.conf import settings
from django.db import models

def lnglat_validator(value):
    if not re.match(r'^[+-]?\d+\.?\d*,[+-]?\d+\.?\d*$', value):
        raise forms.ValidationError('경도/위도를 입력해주세요.')

class Post(models.Model):
    title = models.CharField(max_length = 100)
    content = models.TextField()
    photo = models.ImageField()
    lnglat = models.CharField(max_length=40, blank= True, validators=[lnglat_validator])
    is_public = models.BooleanField(default= False)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.pk])

    @property
    def lng(self):
        if self.lnglat:
            return self.lnglat.split(',')[0]
        return None

    @property
    def lat(self):
        if self.lnglat:
            return self.lnglat.split(',')[1]
        return None

class Comment(models.Model):
    # Post : comment = 1 : N
    post = models.ForeignKey(Post)
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    
    #댓글 최그 순서
    class Meta:
        ordering = ['-id']
    
    def get_edit_url(self):
        return reverse('blog:comment_edit', args = [self.post.pk, self.pk])
    
    def get_delete_url(self):
        return reverse('blog:comment_delete', args = [self.post.pk, self.pk])

blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['message']

blog/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect
from .models import Post, Comment
from .forms import CommentForm

def index(request):
    post_list = Post.objects.all()
    return render(request, 'blog/post_list.html', {
        'post_list': post_list,
    })

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {
        'post' : post,
    })

@login_required
def comment_new(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)

    if request.method == 'POST':
        form = CommentForm(request.POST, request.FILES)
        if form.is_valid():
            comment = form.save(commit = False)
            comment.post = post
            comment.author = request.user
            comment.save()
            return redirect('blog:post_detail', post.pk)
    else:
         form = CommentForm()
    return render(request, 'blog/comment_form.html', {
        'form':form,
    })


@login_required
def comment_edit(request, post_pk, pk):
    comment = get_object_or_404(Comment, pk=pk)
    if comment.author != request.user:
        return redirect(comment.post)

    if request.method == 'POST':
        form = CommentForm(request.POST, request.FILES, instance = comment)
        if form.is_valid():
            comment = form.save()
            return redirect(comment.post)
    else:
         form = CommentForm(instance = comment)
    return render(request, 'blog/comment_form.html', {
        'form':form,
    })

@login_required
def comment_delete(request, post_pk, pk):
    comment = get_object_or_404(Comment, pk=pk)
    if comment.author != request.user:
        return redirect(comment.post)

    if request.method == 'POST':
        comment.delete()
        return redirect(comment.post)
    
    return render(request, 'blog/comment_confirm_delete.html', {
        'comment':comment,
    })

blog/templates/blog/comment_confirm_delete.html
<form action="" method="post">
    {% csrf_token %}    

    정말 삭제하시겠습니까?

    <input type="submit" value="삭제하겠습니까." />   
</form>

blog/templates/blog/comment_form.html
<form action ="" method='post'>
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit">
</form>

blog/templates/blog/layout.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8" />
    <title>{% block title %}여행블로그{% endblock %}</title>
    <!-- <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.7/slate/bootstrap.min.css">
    <script src="//code.jquery.com/jquery-2.2.4.min.js"></script>
    {% block extra_head %}{% endblock %}
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

blog/templates/blog/post_detail.html
{% extends "blog/layout.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block extra_head %}
<style>
post_photo {
        max-width: 100%;
    }
    .post-map {
        width: 300px;
        height: 300px;
    }
</style>
{% if post.lnglat %}
    <script>
    $(function() {
        var lat = {{ post.lat }};
        var lng = {{ post.lng }};
        var myLatLng = { lat: lat, lng: lng};
        var container = $('.post-map')[0];
        var map = new google.maps.Map(container, {
            zoom: 15,
            center: myLatLng
        });
        var marker = new google.maps.Marker({
            position: myLatLng,
            map: map,
            title: 'Hello World!'
        });
    });
    </script>
{% endif %}
<script src="https://maps.googleapis.com/maps/api/js"></script>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Panel heading without title
                    {{ post.title }}
                </div>
                <div class="panel-body">
                    {% if post.photo %}
                        <img src="{{ post.photo.url }}" class="post_photo" /> 
                    {% endif %}
                    <hr/> 

                    <div class="post-map">
                    </div>

                    {{ post.content|linebreaks }}
                    
                    <hr/>

                    <ul>
                    {% for comment in post.comment_set.all %}
                        <li>
                            {{ comment.message }}
                            by {{ comment.author }}
                            at {{ comment.created_at }}
                            {% if comment.author == request.user %}         
                                <a href="{{ comment.get_edit_url }}">
                                    수정
                                </a>
                                <a href="{{ comment.get_delete_url }}" class="text-danger">
                                    삭제
                                </a>
                            {% endif %}
                        </li>
                    {% endfor %}
                    </ul>
                </div>
                <div class="panel-footer">
                    <a href="{% url "blog:index" %}" class="btn btn-default">목록으로</a>
                    <a href="{% url "blog:comment_new" post.pk %}" class="btn btn-primary">댓글쓰기</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends "blog/layout.html" %}

{% block content %}
    <h1>HAWARI 여행 블로그</h1>

    <ul>
    {% for post in post_list %}
    <li>
        <a href ="{% url "blog:post_detail" post.pk %}">
            {{ post.title }}
        </a>
    </li>
    {% endfor %}
    </ul>
{% endblock %}